apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-monitoring.fullname" . }}-secrets
  labels:
    {{- include "employee-monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.config.database.password }}"
  AUDIT_DB_PASSWORD: "{{ .Values.config.auditDatabase.password }}"
  REDIS_PASSWORD: "{{ .Values.config.redis.password }}"
  JWT_SIGNING_KEY: "{{ .Values.config.jwt.signingKey }}"
  OIDC_CLIENT_SECRET: "{{ .Values.config.oidc.clientSecret }}"
  NOTIFICATIONS_EMAIL_PASSWORD: "{{ .Values.config.notifications.email.password }}"
  NOTIFICATIONS_TEAMS_WEBHOOK_URL: "{{ .Values.config.notifications.teams.webhookUrl }}"
  NOTIFICATIONS_SLACK_WEBHOOK_URL: "{{ .Values.config.notifications.slack.webhookUrl }}"